cards = [{"tgt":"I ate [eɪt -US, et -UK] in the morning",
		  "ntv":"Я ел утром",
		  "qst" : "I ... in the morning",
		  "answers":["ate"],
		  "img":"ate2.png"},
{"tgt":"I ran [ræn] yesterday",
 "ntv":"Я бегал вчера",
 "qst" : "I ... yesterday",
 "answers":["ran"],
 "img": "ran2.png"},
{"tgt":"Somebody has stolen my wallet!",
 "ntv":"Кто-то спёр мой кошелёк!",
 "qst":"Somebody has ... my wallet!",
 "answers":["stolen"],
 "img":"stolen3.png"},
{"tgt":"Ouch, seems like I’ve just cut [kʌt] my hand badly",
 "ntv":"Ау, кажется, я только что сильно порезался",
 "qst":"Ouch, seems like I’ve just ... my hand badly",
 "answers":["cut"],
 "img":"cut2.png"},
{"tgt":"Yesterday a colleague of mine drank [dræŋk] 5 mugs of coffee!",
 "ntv":"Вчера один мой коллега выпил 5 кружек кофе!",
 "qst":"Yesterday a colleague of mine ... mugs of coffee!",
 "answers":["drank"],
 "img":"drank2.png"},
{"tgt":"My girlfriend got [ɡɒt - UK, ɡɑːt - US] cold last week but now she’s better",
 "ntv":"На прошлой неделе моя девушка простудилась, но сейчас ей уже лучше",
 "qst":"My girlfriend ... cold last week but now she’s better",
 "answers":["got"],
 "img":"got2.png"},
{"tgt":"They have won [wʌn] the first prize in the competition",
 "ntv":"Они выиграли главный приз в этом соревновании.",
 "qst":"They have ... the first prize in the competition",
 "answers":["won"],
 "img":"won2.png"},
{"tgt":"My friend moved so he had gave [geiv] away a lot of his clothes, stationary and stuff",
 "ntv":"Мой друг переехал, поэтому он раздал много своих вещей, канцелярии и тому подобное",
 "qst":"My friend moved so he had ... away a lot of his clothes, stationary and stuff",
 "answers":["gave"],
 "img":"gave2.png"},
{"tgt":"Have you got [ɡɒt - UK, ɡɑːt - US] a new pair of shoes?",
 "ntv":"Ты купил новую обувь?",
 "qst":"Have you ... a new pair of shoes?",
 "answers":["got"],
 "img":"got2.png"},
{"tgt":"In the morning he ate [eɪt -US, et -UK] all his breakfast very fast because he was in a hurry",
 "ntv":"Утром он очень быстро съел весь свой завтрак, потому что торопился",
 "qst":"In the morning he ... all his breakfast very fast because he ... in a hurry",
 "answers":["ate", "was"],
 "img":"ate2.png"},
{"tgt":"She spoke [spoʊk-US, spəʊk-UK] to her boss about her possible promotion yesterday",
 "ntv":"Вчера она говорила с боссом по поводу своего возможного повышения",
 "qst":"She ... to her boss about her possible promotion yesterday",
 "answers":["spoke"],
 "img":"spoke2.png"},
{"tgt":"I haven’t made [meɪd] a lot of friends at my new workplace so far",
 "ntv":"Я завёл ещё не очень много друзей на новой работе",
 "qst":"I haven’t ... a lot of friends at my new workplace so far",
 "answers":["made"],
 "img":"made2.png"},
{"tgt":"He read [red] the message immediately",
 "ntv":"Он немедленно прочитал сообщение",
 "qst":"He ... the message immediately",
 "answers":["read"],
 "img":"read2.png"},
{"tgt":"Have you ever swam [swæm] in the ocean?",
 "ntv":"Ты когда-нибудь плавал в океане?",
 "qst":"Have you ever ... in the ocean?",
 "answers":["swam"],
 "img":"swam2.png"},
{"tgt":"This client has taken [teɪkən] my brain out!!! I’m pissed off now!!!",
 "ntv":"Этот клиент вынес мне мозг!!! Бесит!!!",
 "qst":"This client has ... my brain out!!! I’m pissed off now!!!",
 "answers":["taken"],
 "img":"taken3.png"},
{"tgt":"In Istiklyal Anton __ across that cool band he had ____ Sonia at one of the lessons.",
 "ntv":"На улице Истикляль Антон наткнулся на ту классную группу, которую когда-то показывал Соне на одном из занятий",
 "qst":"In Istiklyal Anton __ across that cool band he had ____ Sonia at one of the lessons.",
 "answers":[""],
 "img":""},
{"tgt":"Have you _ me your homework yet?",
 "ntv":"Ты уже послал мне свою домашку?",
 "qst":"Have you _ me your homework yet?",
 "answers":[""],
 "img":""},
{"tgt":"My neighbour __ me a very curious book.",
 "ntv":"Мой сосед одолжил мне очень любопытную книгу.",
 "qst":"My neighbour __ me a very curious book.",
 "answers":[""],
 "img":""},
{"tgt":"Somebody __ serenades in our yard every night.",
 "ntv":"Кто-то пел серенады в нашем дворе каждый день.",
 "qst":"Somebody __ serenades in our yard every night.",
 "answers":[""],
 "img":""},
{"tgt":"We _ a nice lesson last week.",
 "ntv":"На прошлой неделе у нас был классный урок.",
 "qst":"We _ a nice lesson last week.",
 "answers":[""],
 "img":""},
{"tgt":"My friend __ past without seeing me at the traffic lights.",
 "ntv":"Мой друг проехал мимо (на машине), не увидев меня на светофоре.",
 "qst":"My friend __ past without seeing me at the traffic lights.",
 "answers":[""],
 "img":""},
]
